### PR TITLE
Add preprocess graph (rotate and crop)

### PR DESCRIPTION
**Pull request by automata**
Need gegl:rotate-on-center support.

### CODE REVIEW

**Comment by jonnor** [comment]
@automata that is not a very good name, too generic, says nothing about what it does. Would prefer something like `rotateandcrop` or `croprotate`.
The GEGL op has been committed, in progress of updating imgflo-dependencies now

**Comment by automata** [comment]
I was calling it `preprocess` thinking about its role, and it would make its semantics valid even if we change its internals in the future (e.g. adding a sharpening filter?). But I agree, that's not informative enough, I can rename it.

**Comment by jonnor** [comment]
That role only makes sense in the particular usecase we have for it (which is outside imgflo-server).

**Comment by automata** [comment]
:+1:

**Comment by jonnor** [comment]
@automata Can you rebase/merge this with master? The GEGL operation should be in now.

**Comment by jonnor** [comment]
Rebased and pushed to master

**Comment by jonnor** [comment]
With one fix, https://github.com/jonnor/imgflo-server/commit/722b3f166b27428cbb490dc67c8a0d12566e147d

**Pull request closed without merging**
